name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: 62796aee7fa0027e8ede6b119ed129ee2071ba2e

  logging:
    level: info

  peer:
    timeout:
      connection: 3s
      queryResponse: 45s
      executeTxResponse: 30s
  eventService:
    timeout:
      connection: 50s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 5s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:

  testchannel:
    orderers:

      - orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local

      - orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-1.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local

      - orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-2.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local

      - orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-3.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local

    peers:

      peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e-1.peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e.default.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - chaicodetest:1.0

organizations:

  62796aee7fa0027e8ede6b119ed129ee2071ba2e:
    mspid: 62796aee7fa0027e8ede6b119ed129ee2071ba2eMSP

    cryptoPath:  /development/python_dev/testsystem/62796aee7fa0027e8ede6b119ed129ee2071ba2e.peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e.default.svc.cluster.local/msp

    peers:

      - peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e-1.peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e.default.svc.cluster.local

    certificateAuthorities:
      - ca-org1

    adminPrivateKey:
      pem: "-----BEGIN PRIVATE KEY----- <etc>"
    signedCert:
      path: "/tmp/somepath/signed-cert.pem"

  ordererorg:
      mspID: "c4369b06a979ebe6c1b580ad81e966c31b19a8e0MSP"

      cryptoPath: /development/python_dev/testsystem/c4369b06a979ebe6c1b580ad81e966c31b19a8e0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local/msp
#orderer eip: 114.116.10.134
orderers:

  orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local:
    url: grpcs://114.116.10.134:30805

    grpcOptions:
      ssl-target-name-override: orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: /development/python_dev/testsystem/c4369b06a979ebe6c1b580ad81e966c31b19a8e0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local/msp/tlscacerts/tlsca.c4369b06a979ebe6c1b580ad81e966c31b19a8e0-cert.pem

  orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-1.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local:
    url: grpcs://114.116.10.134:30806

    grpcOptions:
      ssl-target-name-override: orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-1.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: /development/python_dev/testsystem/c4369b06a979ebe6c1b580ad81e966c31b19a8e0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local/msp/tlscacerts/tlsca.c4369b06a979ebe6c1b580ad81e966c31b19a8e0-cert.pem

  orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-2.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local:
    url: grpcs://114.116.10.134:30807

    grpcOptions:
      ssl-target-name-override: orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-2.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: /development/python_dev/testsystem/c4369b06a979ebe6c1b580ad81e966c31b19a8e0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local/msp/tlscacerts/tlsca.c4369b06a979ebe6c1b580ad81e966c31b19a8e0-cert.pem

  orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-3.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local:
    url: grpcs://114.116.10.134:30808

    grpcOptions:
      ssl-target-name-override: orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0-3.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: /development/python_dev/testsystem/c4369b06a979ebe6c1b580ad81e966c31b19a8e0.orderer-c4369b06a979ebe6c1b580ad81e966c31b19a8e0.default.svc.cluster.local/msp/tlscacerts/tlsca.c4369b06a979ebe6c1b580ad81e966c31b19a8e0-cert.pem

#peer eip: 114.116.10.134
peers:

  peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e-1.peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e.default.svc.cluster.local:
    url: grpcs://114.116.10.134:30611

    eventUrl: grpcs://114.116.10.134:30711

    grpcOptions:
      ssl-target-name-override: peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e-1.peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e.default.svc.cluster.local
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: /development/python_dev/testsystem/62796aee7fa0027e8ede6b119ed129ee2071ba2e.peer-62796aee7fa0027e8ede6b119ed129ee2071ba2e.default.svc.cluster.local/msp/tlscacerts/tlsca.62796aee7fa0027e8ede6b119ed129ee2071ba2e-cert.pem

certificateAuthorities:
  ca-org1:
    url: https://ca_peerOrg1:7054
    httpOptions:
      verify: true
    tlsCACerts:
      path: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/ca_root.pem
      client:
       keyfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client-key.pem
       certfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca-org1